### ISSUE TITLE
Primate should not use oauth2proxy with latest tag

### ISSUE THREAD

**Issue by brumhard** [brumhard/primate#22]
See https://github.com/oauth2-proxy/oauth2-proxy/issues/1669.
At least the used image tag should be configurable.

**Comment by brumhard** [comment]
Fixed by #23

**Comment by DerRockWolf** [comment]
It would be great if you could also release a new version of the helmchart 😄

**Comment by DerRockWolf** [comment]
@brumhard ^^

**Comment by brumhard** [comment]
@DerRockWolf yeah sorry, it's released now.
